Cancels: WIP, no tests yet
samplchallenges/SAMPL-league pull request #182
Opened 2021-11-23 22:32 UTC by robbason

2021-11-25 22:41 UTC, robbason commented on app/referee/tests/test_tasks.py
> +class SynchronousClient:
to me: delete this

2021-11-30 18:01 UTC, mikemhenry requested changes
Looks good, just have one todo

- [x] upload new ever_given version to pypi

2021-11-30 18:02 UTC, mikemhenry commented
Sorry just saw that it is on pypi (had outdated cache when I checked)

2021-11-30 18:05 UTC, mikemhenry approved these changes

2021-12-01 16:46 UTC, megosato approved these changes

2021-12-03 20:37 UTC, robbason commented on app/core/models.py
> +    CANCEL_PENDING = "CANCEL_PENDING"
at least we're not using single-letter codes, like at my other client. started with about six that made sense, C for cancel and so on... now we're almost out of letters.

2021-12-03 20:54 UTC, robbason commented on app/core/models.py
> +        )[0]
figured out a better way to do this

2021-12-03 21:09 UTC, mikemhenry commented on app/core/models.py
> +    CANCEL_PENDING = "CANCEL_PENDING"
Just start using fun letters like æ :)

2021-12-03 22:53 UTC, closed without merging